name: First Workflow
on: 
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print welcome message
        run: echo "Welcome to our first Github actions workflow!"

      - name: checkout repository
        uses: actions/checkout@v6.0.1

      - name: List repo file
        run: ls -la
      
      - name: print the current dir
        run: pwd
        
